# Generated by Django 5.0.7 on 2024-08-24 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_customuser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workspace',
            fields=[
                ('ws_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ws_name', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='workspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('customUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
        ),
    ]
