# Generated by Django 5.0.7 on 2024-08-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workspace_ws_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='ws_url',
        ),
    ]
