# Generated by Django 5.0.7 on 2024-08-28 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_priority_status_playerstats_project_workspacecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.workspace'),
        ),
    ]
