# Generated by Django 5.0.7 on 2024-08-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_priority_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_member_bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lead', 'Lead'), ('Team member', 'Team member')], max_length=12)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(through='users.project_member_bridge', to='users.customuser'),
        ),
    ]
