# Generated by Django 5.0.7 on 2024-08-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_project_member_bridge_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_member_bridge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
