# Generated by Django 5.0.7 on 2024-08-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_issue_issue_assignee_bridge_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.issue'),
        ),
    ]
