# Generated by Django 5.0.7 on 2024-08-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_issue_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='users.issue'),
        ),
    ]
