# Generated by Django 5.0.7 on 2024-09-01 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_issue_parent_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("verification_code", models.CharField(max_length=6)),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
