# Generated by Django 5.0.7 on 2024-09-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_issue_parent_task'),
        ('users', '0015_emailverification'),
    ]

    operations = [
    ]
