# Generated by Django 5.0.7 on 2024-09-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_issue_description'),
        ('users', '0017_priority_icon'),
    ]

    operations = [
    ]
