# Generated by Django 5.0.7 on 2024-09-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_0017_alter_issue_description_0017_priority_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue_assignee_bridge',
            unique_together={('assignee', 'issue')},
        ),
        migrations.AlterUniqueTogether(
            name='project_member_bridge',
            unique_together={('team_member', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'customUser')},
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.issue')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comments')),
            ],
        ),
    ]
