# Generated by Django 5.0.7 on 2024-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_issue_overall_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Closed', 'Closed')], max_length=100),
        ),
    ]
