# Generated by Django 5.0.7 on 2024-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
