# Generated by Django 5.0.7 on 2024-10-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['priority__id']},
        ),
    ]
