# Generated by Django 5.0.7 on 2024-10-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_issue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_comments', to='users.customuser'),
        ),
    ]
