# Generated by Django 5.0.7 on 2024-10-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_comments_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
